#pragma once
#ifndef _ANIMATIONTYPES_H
#define _ANIMATIONTYPES_H

// 新增植物/僵尸时，在此加一个动画类型枚举；完整新增步骤见
// Game/Plant/GameDataManager.cpp 的 InitializeHardcodedData 顶部说明。
enum class AnimationType
{
	ANIM_NONE,
	ANIM_SUN,

	ANIM_SUNFLOWER,
	ANIM_PEASHOOTER,
	ANIM_CHERRYBOMB,
	ANIM_WALLNUT,
	ANIM_POTATOMINE,
	ANIM_SNOWPEASHOOTER,
	ANIM_CHOMPER,
	ANIM_REPEAT,
	ANIM_PUFFSHROOM,
	ANIM_SUNSHROOM,
	ANIM_FUMESHROOM,
	// ANIM_GRAVEBUSTER,
	ANIM_HYPER,
	ANIM_SCAREDYSHROOM,
	ANIM_ICE_SHROOM,
	ANIM_ICEFUMESHROOM,
	ANIM_DOOM_SHROOM,
	ANIM_LILYPAD,

	ANIM_NORMAL_ZOMBIE,
	ANIM_CONE_ZOMBIE,
	ANIM_POLEVAULTER_ZOMBIE,
	ANIM_BUCKET_ZOMBIE,   // 铁通僵尸
	ANIM_PAPER_ZOMBIE,    // 报纸僵尸
	ANIM_DOOR_ZOMBIE,      // 铁门僵尸
	ANIM_FOOTBALL_ZOMBIE,  // 橄榄僵尸
	ANIM_PINK_FOOTBALL_ZOMBIE, // 粉色橄榄球僵尸
	ANIM_DANCE_ZOMBIE,     // 舞王僵尸
	ANIM_DANCERWITH_ZOMBIE, // 伴舞僵尸
	ANIM_ELITE_DANCE_ZOMBIE, // 精英舞王僵尸

	ANIM_ZOMBIE_CHARRED,

	ANIM_LAWNMOWER,
	ANIM_POOL_NORMAL_ZOMBIE,
	ANIM_POOL_CONE_ZOMBIE,
	ANIM_POOL_BUCKET_ZOMBIE,
	ANIM_POOL_CLEANER,
	ANIM_ELITE_SCAREDYSHROOM, // 复用 ScaredyShroom reanim；追加在末尾避免旧动画枚举值错位
	ANIM_SQUASH, // 经典倭瓜；追加在末尾避免旧动画枚举值错位
};

#endif
