#pragma once
#ifndef _ANIMATIONTYPES_H
#define _ANIMATIONTYPES_H

// 新增植物/僵尸时，在此加一个动画类型枚举；完整新增步骤见
// Game/Plant/GameDataManager.cpp 的 InitializeHardcodedData 顶部说明。
enum class AnimationType
{
	ANIM_NONE,
	ANIM_SUN,

	ANIM_SUNFLOWER,
	ANIM_PEASHOOTER,
	ANIM_CHERRYBOMB,
	ANIM_WALLNUT,
	ANIM_POTATOMINE,
	ANIM_SNOWPEASHOOTER,
	ANIM_CHOMPER,
	ANIM_REPEAT,
	ANIM_PUFFSHROOM,

	ANIM_NORMAL_ZOMBIE,
	ANIM_CONE_ZOMBIE,
	ANIM_POLEVAULTER_ZOMBIE,
	ANIM_BUCKET_ZOMBIE,   //铁通僵尸

	ANIM_ZOMBIE_CHARRED,

	ANIM_LAWNMOWER,
};

#endif