#pragma once
#ifndef _PLANTTYPE_H
#define _PLANTTYPE_H

constexpr int NULL_PLANT_ID = -1024;

enum class PlantType
{
	PLANT_PEASHOOTER,
	PLANT_SUNFLOWER,
	PLANT_CHERRYBOMB,
	PLANT_WALLNUT,
	PLANT_POTATOMINE,
	PLANT_SNOWPEA,
	PLANT_CHOMPER,
	PLANT_REPEATER,
	PLANT_PUFFSHROOM,
	PLANT_SUNSHROOM,
	PLANT_FUMESHROOM,
	// PLANT_GRAVEBUSTER,
	PLANT_HYPNOSHROOM,
	PLANT_SCAREDYSHROOM,
	PLANT_ICESHROOM,
	PLANT_ICEFUMESHROOM,	// 寒冰大喷菇（自创变种）；冒险解锁顺序由 AdventureProgression 奖励表决定
	PLANT_DOOMSHROOM,
	PLANT_LILYPAD,
	PLANT_SQUASH,
	PLANT_THREEPEATER,
	PLANT_TANGLEKELP,
	PLANT_JALAPENO,
	PLANT_SPIKEWEED,
	PLANT_TORCHWOOD,
	PLANT_TALLNUT,
	PLANT_SEASHROOM,
	PLANT_PLANTERN,
	PLANT_CACTUS,
	PLANT_BLOVER,
	PLANT_SPLITPEA,
	PLANT_STARFRUIT,
	PLANT_PUMPKINSHELL,
	PLANT_MAGNETSHROOM,
	PLANT_CABBAGEPULT,
	PLANT_FLOWERPOT,
	PLANT_KERNELPULT,
	PLANT_INSTANT_COFFEE,
	PLANT_GARLIC,
	PLANT_UMBRELLA,
	PLANT_MARIGOLD,
	PLANT_MELONPULT,
	PLANT_GATLINGPEA,
	PLANT_TWINSUNFLOWER,
	PLANT_GLOOMSHROOM,
	PLANT_CATTAIL,
	PLANT_WINTERMELON,
	PLANT_GOLD_MAGNET,
	PLANT_SPIKEROCK,
	PLANT_COBCANNON,
	PLANT_IMITATER,
	PLANT_EXPLODE_O_NUT,
	PLANT_GIANT_WALLNUT,
	PLANT_SPROUT,
	PLANT_LEFTPEATER,
	PLANT_ELITE_SCAREDYSHROOM,	// 精英胆小菇；追加在末尾以保持旧存档植物整数 ID
	PLANT_TOXICPEASHOOTER,	// 毒囊射手；继续追加在末尾以保持旧存档植物整数 ID
	PLANT_GROUNDINGSHROOM,	// 接地菇；5-9 奖励，追加在末尾以保持旧存档植物整数 ID
	PLANT_LIGHTNINGRODPOT,	// 避雷花盆；6-4 奖励，花盆承载层紫卡升级
	PLANT_SNOWANCHORNUT,	// 雪锚果；7-1 奖励，在真实冻土中提供一次冬季冲击整形
	PLANT_MELTSNOWPULT,	// 融雪投手；7-2 奖励，准确寒潮预报装填三发盐晶弹
	PLANT_FROSTMINE,	// 伏霜雷；7-4 奖励，预报校准并在实际冻土中埋伏地面目标
	NUM_PLANT_TYPES,
};

#endif
