#pragma once
#ifndef _PLANTTYPE_H
#define _PLANTTYPE_H

enum class PlantType
{
	PLANT_NONE,
	PLANT_PEASHOOTER,
	PLANT_SUNFLOWER,
	PLANT_WALLNUT,
	PLANT_CHERRYBOMB,
	PLANT_POTATOMINE,
	PLANT_SNOWPEA,
	PLANT_CHOMPER,
	PLANT_REPEATER,
	PLANT_PUFFSHROOM,
	PLANT_SCAREDYSHROOM,
	PLANT_FUMESHROOM,
	PLANT_GRAVEBUSTER,
	PLANT_HYPNOSHROOM,
	PLANT_SPRINGMUSHROOM,
	PLANT_CACTUS,
	PLANT_TORCHWOOD,
	PLANT_TALLNUT,
	PLANT_SPIKEWEED,
	PLANT_JALAPENO,
	PLANT_SQUASH,
	PLANT_THREEPEATER,
	PLANT_SPIKEROCK,
	PLANT_COBCANNON,
	PLANT_MAGNETSHROOM,
	PLANT_COFFEEBEAN,
	PLANT_GARLIC,
	PLANT_IMITATER,
};

#endif