#pragma once
#ifndef _ZOMBIE_TYPE_H_
#define _ZOMBIE_TYPE_H_

constexpr int NULL_ZOMBIE_ID = -1024;

enum class HelmType {
	HELMTYPE_NONE,
	HELMTYPE_TRAFFIC_CONE,	//路障
	HELMTYPE_BUCKET,			//铁桶
	HELMTYPE_FOOTBALL,		//橄榄球
	HELMTYPE_DIGGER,		//镐子
	HELMTYPE_BOBSLED,		//雪橇
	HELMTYPE_WALLNUT,		//坚果
	HELMTYPE_TALLNUT		//高坚果
};

enum class ShieldType {
	SHIELDTYPE_NONE,
	SHIELDTYPE_DOOR,		//铁门
	SHIELDTYPE_NEWSPAPER,	//报纸
	SHIELDTYPE_LADDER		//梯子
};

enum class ArmorBrokenState {
	NONE,
	NO_BROKEN,
	A_LITTLE_BROKEN,
	REALLY_BROKEN,
};

enum class ZombieType {
	ZOMBIE_NORMAL,
	ZOMBIE_TRAFFIC_CONE,
	ZOMBIE_POLEVAULTER,
	ZOMBIE_BUCKET,
	ZOMBIE_FASTBUCKET,
	ZOMBIE_NEWSPAPER,
	ZOMBIE_FASTPAPER,	// 加强版读报僵尸
	ZOMBIE_DOOR,
	ZOMBIE_FOOTBALL,
	ZOMBIE_DANCER,
	ZOMBIE_BACKUP_DANCER,
	ZOMBIE_PINK_FOOTBALL,
	ZOMBIE_ELITE_DANCER,
	ZOMBIE_REINFORCED_DOOR,
	ZOMBIE_POOL_NORMAL,
	ZOMBIE_POOL_CONE,
	ZOMBIE_POOL_BUCKET,

	// ↓ 哨兵：置于全部已实现僵尸之后，使 [0,NUM_ZOMBIE_TYPES) 只覆盖已实现类型，
	//   生存模式随机抽取据此绝不会抽到下方未实现僵尸。
	//   注：Board::LoadSpawnListFromJson 亦以此为上界校验 JSON 僵尸ID，效果一致。
	NUM_ZOMBIE_TYPES,

	ZOMBIE_SNORKEL,
	ZOMBIE_ZAMBONI,		// 冰车
	ZOMBIE_BOBSLED,		// 小队
	ZOMBIE_DOLPHIN_RIDER,
	ZOMBIE_JACK_IN_THE_BOX,
	ZOMBIE_BALLOON,
	ZOMBIE_DIGGER,
	ZOMBIE_POGO,
	ZOMBIE_YETI,
	ZOMBIE_BUNGEE,
	ZOMBIE_LADDER,
	ZOMBIE_CATAPULT,
	ZOMBIE_GARGANTUAR,
	ZOMBIE_IMP,
	ZOMBIE_BOSS,
	ZOMBIE_PEA_HEAD,
	ZOMBIE_WALLNUT_HEAD,
	ZOMBIE_JALAPENO_HEAD,
	ZOMBIE_GATLING_HEAD,
	ZOMBIE_SQUASH_HEAD,
	ZOMBIE_TALLNUT_HEAD,
	ZOMBIE_REDEYE_GARGANTUAR,
};

#endif
