#pragma once
#ifndef _RESOURCE_KEYS_H
#define _RESOURCE_KEYS_H

#include <string>

// RKEY(X) 定义一个「键值 == 键名」的资源键常量，消除 IMAGE_X = "IMAGE_X" 这类重复书写：
//   RKEY(IMAGE_PEASHOOTER);  ==>  inline const std::string IMAGE_PEASHOOTER = "IMAGE_PEASHOOTER";
// 仅用于「键名 == 键值」的常量；键名 ≠ 键值的别名（如 IMAGE_APPROACHING、SOUND_THROW、
// REANIM_* 的 CamelCase、字体路径）仍显式书写，因为那一行携带了真信息。
// 用 inline 变量：跨翻译单元只构造一份（旧的 const std::string 在命名空间作用域是内部链接，
// 每个 #include 本头的 .cpp 都会各构造一整套，纯属浪费）。
#define RKEY(n) inline const std::string n = #n

namespace ResourceKeys
{
	namespace Textures
	{
		RKEY(IMAGE_KID);
		inline const std::string IMAGE_GLOWING = "IMAGE_AWARDGLOW";
		inline const std::string IMAGE_TROPHY = "IMAGE_TROPHY_HI_RES";
		RKEY(IMAGE_OPTIONS_CHECKBOX0);
		RKEY(IMAGE_OPTIONS_CHECKBOX1);
		RKEY(IMAGE_SEEDCHOOSER_BUTTON2);
		RKEY(IMAGE_SEEDCHOOSER_BUTTON2_GLOW);
		RKEY(IMAGE_OPTIONS_SLIDERKNOB2);
		RKEY(IMAGE_OPTIONS_SLIDERSLOT);
		RKEY(IMAGE_SELECTORSCREEN_ADVENTURE_BUTTON);
		RKEY(IMAGE_SELECTORSCREEN_ADVENTURE_HIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_ALMANAC);
		RKEY(IMAGE_SELECTORSCREEN_ALMANACHIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_BG);
		RKEY(IMAGE_SELECTORSCREEN_BG_CENTER);
		RKEY(IMAGE_SELECTORSCREEN_BG_LEFT);
		RKEY(IMAGE_SELECTORSCREEN_BG_RIGHT);
		RKEY(IMAGE_SELECTORSCREEN_CHALLENGES_BUTTON);
		RKEY(IMAGE_SELECTORSCREEN_CHALLENGES_HIGHLIGHT);
		// 挑战模式选择界面（GameSelectScene）——键由 Challenge_*.png 文件名自动派生
		RKEY(IMAGE_CHALLENGE_BACKGROUND);
		RKEY(IMAGE_CHALLENGE_WINDOW);
		RKEY(IMAGE_CHALLENGE_WINDOW_HIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_FLOWER1);
		RKEY(IMAGE_SELECTORSCREEN_FLOWER2);
		RKEY(IMAGE_SELECTORSCREEN_FLOWER3);
		RKEY(IMAGE_SELECTORSCREEN_GAME);
		RKEY(IMAGE_SELECTORSCREEN_GAME_SHADOW);
		RKEY(IMAGE_SELECTORSCREEN_HELP1);
		RKEY(IMAGE_SELECTORSCREEN_HELP2);
		RKEY(IMAGE_SELECTORSCREEN_OPTIONS1);
		RKEY(IMAGE_SELECTORSCREEN_OPTIONS2);
		RKEY(IMAGE_SELECTORSCREEN_QUIT1);
		RKEY(IMAGE_SELECTORSCREEN_QUIT2);
		RKEY(IMAGE_SELECTORSCREEN_STARTADVENTURE_BUTTON1);
		RKEY(IMAGE_SELECTORSCREEN_STARTADVENTURE_HIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_STORE);
		RKEY(IMAGE_SELECTORSCREEN_STOREHIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_SURIVAL);
		RKEY(IMAGE_SELECTORSCREEN_SURIVAL_SHADOW);
		RKEY(IMAGE_CARD_BK);
		RKEY(IMAGE_SEEDBANK_LONG);
		RKEY(IMAGE_SEEDCHOOSER_BACKGROUND);
		RKEY(IMAGE_SEEDCHOOSER_BUTTON);
		RKEY(IMAGE_SEEDCHOOSER_BUTTON_DISABLED);
		RKEY(IMAGE_SEEDPACKETNORMAL);
		RKEY(IMAGE_BACKGROUND_DAY);
		RKEY(IMAGE_BACKGROUND_NIGHT);
		RKEY(IMAGE_SHOVELBANK);
		RKEY(IMAGE_OPTIONS_MENUBACK);
		RKEY(IMAGE_BUTTONBIG);
		RKEY(IMAGE_BUTTONSMALL);
		RKEY(IMAGE_MESSAGEBOX);
		RKEY(IMAGE_OPTIONS_BACKTOGAMEBUTTON0);
		RKEY(IMAGE_OPTIONS_BACKTOGAMEBUTTON_LIGHT);
		inline const std::string IMAGE_FLAG_METER = "IMAGE_FLAGMETER_PART_0";
		inline const std::string IMAGE_FLAG_METERFULL = "IMAGE_FLAGMETER_PART_1";
		RKEY(IMAGE_FLAGMETERLEVELPROGRESS);
		inline const std::string IMAGE_FLAGMETER_PART_HEAD = "IMAGE_FLAGMETERPARTS_PART_0";
		inline const std::string IMAGE_FLAGMETER_PART_STICK = "IMAGE_FLAGMETERPARTS_PART_1";
		inline const std::string IMAGE_FLAGMETER_PART_FLAG = "IMAGE_FLAGMETERPARTS_PART_2";

		RKEY(IMAGE_SHOVEL);

		inline const std::string IMAGE_HUGE_WAVE_APPROACHING = "IMAGE_APPROACHING";

		inline const std::string IMAGE_FINAL_WAVE = "IMAGE_FINALWAVE";

		RKEY(IMAGE_PLANTSHADOW);
		RKEY(IMAGE_PLANTSHADOW2);

		RKEY(IMAGE_ZOMBIE_BACKUP_OUTERARM_UPPER_BONE);
		RKEY(IMAGE_ZOMBIE_BALLOON_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BOBSLED_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BOSS_ARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BUNGI_LEFTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BUNGI_RIGHTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_DIGGER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_DISCO_OUTERARM_UPPER_BONE);
		RKEY(IMAGE_ZOMBIE_DOLPHINRIDER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_FOOTBALL_LEFTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_PINKFOOTBALL_LEFTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_PINKFOOTBALL_HELMET2);
		RKEY(IMAGE_ZOMBIE_PINKFOOTBALL_HELMET3);
		RKEY(IMAGE_ZOMBIE_JACKSON_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_LADDER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_PAPER_LEFTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_POGO_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_POLEVAULTER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_SNORKLE_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_YETI_OUTERARM_UPPER2);

		RKEY(IMAGE_PROJECTILECACTUS);
		RKEY(IMAGE_PROJECTILEPEA);
		RKEY(IMAGE_PROJECTILESNOWPEA);
		RKEY(IMAGE_PROJECTILE_STAR);

		// 植物图片（IMAGE_ + 大写文件名）
		RKEY(IMAGE_PEASHOOTER);
		RKEY(IMAGE_SUNFLOWER);
		RKEY(IMAGE_CHERRYBOMB);
		RKEY(IMAGE_WALLNUT);
		RKEY(IMAGE_POTATOMINE);
		RKEY(IMAGE_SNOWPEASHOOTER);
		RKEY(IMAGE_CHOMPER);
		RKEY(IMAGE_REPEATER);
		RKEY(IMAGE_PUFFSHROOM);
		RKEY(IMAGE_SUNSHROOM);
		RKEY(IMAGE_FUMESHROOM);
		RKEY(IMAGE_GRAVEBUSTER);
		RKEY(IMAGE_HYPNOSHROOM);
		RKEY(IMAGE_SCAREDYSHROOM);
		RKEY(IMAGE_ICESHROOM);
		RKEY(IMAGE_ICEFUMESHROOM);
		RKEY(IMAGE_ICETRAP);		// 冻结僵尸脚底冰晶（image 根目录 icetrap.png）
		RKEY(IMAGE_CRATER_PART_0);		// 毁灭菇弹坑（crater.png 1行2列分份：0=白天）
		RKEY(IMAGE_CRATER_PART_1);		// 1=黑夜
		RKEY(IMAGE_CRATER_FADING_PART_0);	// 弹坑后半程消退版（同 0=白天/1=黑夜）
		RKEY(IMAGE_CRATER_FADING_PART_1);
		RKEY(IMAGE_DOOMSHROOM);
		RKEY(IMAGE_SQUASH);
		RKEY(IMAGE_THREEPEATER);
		RKEY(IMAGE_TANGLEKELP);
		RKEY(IMAGE_JALAPENO);
		RKEY(IMAGE_TORCHWOOD);
	}

	namespace Particles
	{
		RKEY(PARTICLE_WINDSTREAK);
		inline const std::string PARTICLE_ZOMBIE_HEAD = "PARTICLE_ZOMBIEHEAD";
		RKEY(PARTICLE_EXPLOSIONCLOUD);
		inline const std::string PARTICLE_ZOMBIE_BACKUPDANCERHEAD = "PARTICLE_ZOMBIEBACKUPDANCERHEAD";
		inline const std::string PARTICLE_ZOMBIE_BACKUPDANCERHEAD_DISCO = "PARTICLE_ZOMBIEBACKUPDANCERHEAD_DISCO";
		inline const std::string PARTICLE_ZOMBIE_BOBSLEDHEAD = "PARTICLE_ZOMBIEBOBSLEDHEAD";
		inline const std::string PARTICLE_ZOMBIE_DANCERHEAD = "PARTICLE_ZOMBIEDANCERHEAD";
		inline const std::string PARTICLE_ZOMBIE_DANCERHEAD_DISCO = "PARTICLE_ZOMBIEDANCERHEAD_DISCO";
		inline const std::string PARTICLE_ZOMBIE_DIGGERARM = "PARTICLE_ZOMBIEDIGGERARM";
		inline const std::string PARTICLE_ZOMBIE_DIGGERHEAD = "PARTICLE_ZOMBIEDIGGERHEAD";
		inline const std::string PARTICLE_ZOMBIE_DOLPHINRIDERHEAD = "PARTICLE_ZOMBIEDOLPHINRIDERHEAD";
		inline const std::string PARTICLE_ZOMBIE_FOOTBALLHEAD = "PARTICLE_ZOMBIEFOOTBALLHEAD";
		inline const std::string PARTICLE_ZOMBIE_IMPHEAD = "PARTICLE_ZOMBIEIMPHEAD";
		inline const std::string PARTICLE_ZOMBIE_LADDERHEAD = "PARTICLE_ZOMBIELADDERHEAD";
		inline const std::string PARTICLE_ZOMBIE_POGOHEAD = "PARTICLE_ZOMBIEPOGOHEAD";
		inline const std::string PARTICLE_ZOMBIE_POLEVAULTERHEAD = "PARTICLE_ZOMBIEPOLEVAULTERHEAD";
		inline const std::string PARTICLE_ZOMBIE_YETIHEAD = "PARTICLE_ZOMBIEYETIHEAD";
		RKEY(PARTICLE_ZOMBIEARM);
	}

	namespace Fonts
	{
		inline const std::string FONT_FZCQ = "./font/fzcq.ttf";
		inline const std::string FONT_FZJZ = "./font/fzjz.ttf";
		inline const std::string FONT_CONTINUUMBOLD = "./font/ContinuumBold.ttf";
	}

	namespace Sounds
	{
		RKEY(SOUND_BLEEP);
		RKEY(SOUND_BUTTONCLICK);
		RKEY(SOUND_CERAMIC);
		RKEY(SOUND_CHOOSEPLANT1);
		RKEY(SOUND_CHOOSEPLANT2);
		RKEY(SOUND_GRAVEBUTTON);
		RKEY(SOUND_MAINMENU);
		RKEY(SOUND_PAUSE);
		RKEY(SOUND_SHOVEL);
		RKEY(SOUND_COLLECTSUN);
		RKEY(SOUND_CLICKFAILED);
		RKEY(SOUND_AFTERHUGEWAVE);
		RKEY(SOUND_FINALWAVE);
		RKEY(SOUND_FIRSTWAVE);
		RKEY(SOUND_LAWNMOWER);
		RKEY(SOUND_LOSTGAME);
		RKEY(SOUND_POOL_CLEANER);
		RKEY(SOUND_READYSETPLANT);
		RKEY(SOUND_WINMUSIC);
		inline const std::string SOUND_ZOMBIE_EAT = "SOUND_CHOMP";
		inline const std::string SOUND_ZOMBIE_EAT2 = "SOUND_CHOMP2";
		inline const std::string SOUND_ZOMBIE_FINISHEAT = "SOUND_FINISHEATING";
		RKEY(SOUND_HUGEWAVE);
		RKEY(SOUND_ARM_HEAD_DROP);
		RKEY(SOUND_FROZEN);		// 寒冰菇全场冻结（原版 frozen.ogg）
		RKEY(SOUND_RAIN);			// 原版暴风雨夜循环环境音（rain.ogg）
		inline const std::string SOUND_POLEVAULT_JUMP = "SOUND_POLEVAULT";

		RKEY(SOUND_CLICKSEED);
		RKEY(SOUND_DELETEPLANT);
		RKEY(SOUND_PLANT);
		RKEY(SOUND_PLANT_ONWATER);
		RKEY(SOUND_POTATO_MINE);
		RKEY(SOUND_SQUASH_HMM);
		RKEY(SOUND_SQUASH_HMM2);
		inline const std::string SOUND_SHOOTER_SHOOT = "SOUND_THROW";
		inline const std::string SOUND_SHOOTER_SHOOT2 = "SOUND_THROW2";
		RKEY(SOUND_CHERRYBOMB);
		RKEY(SOUND_DOOMSHROOM);				// 毁灭菇爆炸（原版 doomshroom.ogg）
		RKEY(SOUND_REVERSE_EXPLOSION);		// 毁灭菇引爆前吸气充能声（原版 reverse_explosion.ogg）

		// 子弹击中僵尸
		RKEY(SOUND_SNOW_PEA_SPARKLES);
		inline const std::string SOUND_PEABULLET_HIT_BODY1 = "SOUND_SPLAT";
		inline const std::string SOUND_PEABULLET_HIT_BODY2 = "SOUND_SPLAT2";
		inline const std::string SOUND_PEABULLET_HIT_BODY3 = "SOUND_SPLAT3";
		RKEY(SOUND_HITCONE);
		RKEY(SOUND_HITCONE2);
		RKEY(SOUND_IRONHIT);
		RKEY(SOUND_IRONHIT2);
	}

	namespace Music
	{
		RKEY(MUSIC_MAINMENU);
		RKEY(MUSIC_CHOOSEYOURSEEDS);
		RKEY(MUSIC_DAY);
		RKEY(MUSIC_FOG);
		RKEY(MUSIC_LOONBOON);
		RKEY(MUSIC_NIGHT);
		RKEY(MUSIC_POOL);
		RKEY(MUSIC_ROOF);
		RKEY(MUSIC_ZENGARDEN);
	}

	// 新增植物/僵尸/资源时，在对应 namespace 加资源键；完整新增步骤见
	// Game/Plant/GameDataManager.cpp 的 InitializeHardcodedData 顶部说明。
	// reanim 键名 ≠ 键值（值是 CamelCase 文件名），故全部显式书写，不用 RKEY。
	namespace Reanimations
	{
		inline const std::string REANIM_SUN = "Sun";

		inline const std::string REANIM_SUNFLOWER = "SunFlower";
		inline const std::string REANIM_PEASHOOTER = "PeaShooter";
		inline const std::string REANIM_CHERRYBOMB = "CherryBomb";
		inline const std::string REANIM_WALLNUT = "Wallnut";
		inline const std::string REANIM_POTATOMINE = "PotatoMine";
		inline const std::string REANIM_SNOWPEASHOOTER = "SnowPeaShooter";

		inline const std::string REANIM_NORMAL_ZOMBIE = "NormalZombie";
		inline const std::string REANIM_CONE_ZOMBIE = "ConeZombie";
		inline const std::string REANIM_POLEVAULTER_ZOMBIE = "PolevaulterZombie";
		inline const std::string REANIM_BUCKET_ZOMBIE = "BucketZombie";
		inline const std::string REANIM_ZOMBIE_ELITE_JACKSON = "ZombieEliteJackson";

		inline const std::string REANIM_ZOMBIE_CHARRED = "Zombie_Charred";

		inline const std::string REANIM_LAWNMOWER = "LawnMower";
	}
}

#undef RKEY   // 不把内部宏泄漏给包含本头的翻译单元

#endif
